import json

filepath = 'D:/Company/chemistry_anim/packages/c04-periodic-table/src/data/elements.ts'

with open(filepath, 'rb') as f:
    raw = f.read()
content = raw.replace(b'\r\n', b'\n').replace(b'\r', b'\n').decode('utf-8')

def ts_str(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        escaped = v.replace('\\', '\\\\').replace('"', '\\"')
        return f'"{escaped}"'
    raise ValueError(f"Unknown type: {type(v)}")

def element_to_ts(el):
    lines = ['  {']
    for k, v in el.items():
        if isinstance(v, list):
            if len(v) == 0:
                lines.append(f'    {k}: [],')
            else:
                lines.append(f'    {k}: [')
                for item in v:
                    lines.append(f'      {ts_str(item)},')
                lines.append('    ],')
        else:
            lines.append(f'    {k}: {ts_str(v)},')
    lines.append('  }')
    return '\n'.join(lines)

LANT_CHEM = "镧系元素化学性质极为相似，均以 +3 氧化态为主（4f 电子被外层 5s²5p⁶ 屏蔽）。在空气中易被氧化，与水缓慢反应生成 Ln(OH)₃。"
LANT_EDU = ["[拓展] 4f 电子填充、镧系收缩现象"]
ACT_EDU = ["[高中选修] 核裂变与核聚变原理、放射性"]

elements = [
  # ── Period 5 ──────────────────────────────────────────────
  dict(atomicNumber=51, symbol="Sb", nameZh="锑", nameEn="Antimony",
       atomicMass="121.76", category="metalloid", period=5, group=15, groupLabel="VA",
       stateAtRoomTemp="银白色有光泽固体", density="6.68 g/cm³",
       meltingPoint=630.63, boilingPoint=1587, electronegativity=2.05,
       electronConfiguration="[Kr] 4d¹⁰ 5s² 5p³", oxidationStates="+3, +5",
       chemicalProperties="锑质脆，有金属光泽，是典型的类金属。Sb₂O₃ 与卤素阻燃剂协效使用，是重要的阻燃助剂。锑不溶于稀盐酸，与浓 HNO₃ 反应生成 Sb₂O₅。",
       history="古埃及人已用辉锑矿（Sb₂S₃）磨粉作眼影，元素符号 Sb 来自拉丁语 stibium。16 世纪巴西利乌斯·瓦伦蒂努斯对其有详细记载。",
       applications="阻燃剂（Sb₂O₃ 与卤素协效）、铅蓄电池合金（提高极板硬度）、半导体材料、焊料合金。",
       funFact="古埃及人用辉锑矿磨成的黑色粉末作眼影，现代研究发现此粉末在潮湿环境中会生成抗菌化合物，这可能是古埃及人眼部感染率较低的原因之一。",
       educationalLinks=[]),

  dict(atomicNumber=52, symbol="Te", nameZh="碲", nameEn="Tellurium",
       atomicMass="127.60", category="metalloid", period=5, group=16, groupLabel="VIA",
       stateAtRoomTemp="银白色固体", density="6.24 g/cm³",
       meltingPoint=449.51, boilingPoint=988, electronegativity=2.1,
       electronConfiguration="[Kr] 4d¹⁰ 5s² 5p⁴", oxidationStates="-2, +4, +6",
       chemicalProperties="碲是典型的类金属，具有半导体性质，导电性随温度升高而增强。碲化镉（CdTe）是重要的薄膜太阳能电池材料。碲化铋（Bi₂Te₃）是室温附近最佳热电材料。",
       history="1782 年穆勒·冯·赖兴施泰因在特兰西瓦尼亚矿石中发现，1798 年克拉普罗特命名，tellurium 来自拉丁语 tellus（地球）。",
       applications="碲化镉（CdTe）薄膜太阳能电池、碲化铋热电器件（半导体制冷/温差发电）、碲化镉汞红外探测器。",
       funFact="碲是地壳中极为稀少的稳定元素之一，丰度比铂还低。随着碲化镉薄膜太阳能电池的兴起，碲已成为战略性稀缺资源。",
       educationalLinks=[]),

  dict(atomicNumber=53, symbol="I", nameZh="碘", nameEn="Iodine",
       atomicMass="126.90", category="halogen", period=5, group=17, groupLabel="VIIA",
       stateAtRoomTemp="紫黑色固体（加热直接升华）", density="4.93 g/cm³",
       meltingPoint=113.7, boilingPoint=184.3, electronegativity=2.66,
       electronConfiguration="[Kr] 4d¹⁰ 5s² 5p⁵", oxidationStates="-1, +5, +7",
       chemicalProperties="碘单质是紫黑色固体，加热后直接升华为紫色蒸气。碘遇淀粉变蓝是最经典的检验反应。碘在水中溶解度很低，但易溶于 KI 溶液（生成 I₃⁻）和有机溶剂（在 CCl₄ 中呈紫色）。碘的氧化性在卤素中最弱。",
       history="1811 年法国化学家库尔图瓦从海藻灰中发现，命名来自希腊语 iodes（紫色）。碘是人体必需微量元素，用于合成甲状腺素。",
       applications="碘酒（医用消毒）、碘化钾（碘盐，预防甲状腺肿大）、碘化银（人工降雨）、有机合成试剂。",
       funFact="碘遇淀粉变蓝并非生成了新化合物，而是碘分子（I₂）嵌入直链淀粉螺旋通道中，改变了碘分子的电子跃迁能量，从而呈现深蓝色。",
       educationalLinks=["[初中] 碘遇淀粉变蓝", "[高中必修] 卤素性质递变、碘的升华"]),

  dict(atomicNumber=54, symbol="Xe", nameZh="氙", nameEn="Xenon",
       atomicMass="131.29", category="noble-gas", period=5, group=18, groupLabel="0族",
       stateAtRoomTemp="无色气体", density="5.90 g/L（0°C）",
       meltingPoint=-111.75, boilingPoint=-108.12, electronegativity=2.6,
       electronConfiguration="[Kr] 4d¹⁰ 5s² 5p⁶", oxidationStates="0, +2, +4, +6",
       chemicalProperties="氙是第一个被证实能形成化合物的稀有气体。已知化合物有 XeF₂、XeF₄、XeF₆ 等氟化物，均为强氧化剂。XeO₃ 等含氧化合物也已被合成。",
       history="1898 年雷姆赛和特拉弗斯发现，命名来自希腊语 xenos（陌生人）。1962 年巴特利特合成 XePtF₆，打破了稀有气体不能形成化合物的传统观念。",
       applications="氙气灯（HID 大灯、电影放映机）、全身麻醉（医用）、离子推进器（航天）、闪光摄影。",
       funFact="1962 年巴特利特合成了首个稀有气体化合物 XePtF₆，打破了化学界数十年的错误认知——此前人们认为稀有气体绝对不能形成化合物。",
       educationalLinks=["[高中选修] 稀有气体化合物的发现是化学史上的里程碑"]),

  # ── Period 6 ──────────────────────────────────────────────
  dict(atomicNumber=55, symbol="Cs", nameZh="铯", nameEn="Cesium",
       atomicMass="132.91", category="alkali-metal", period=6, group=1, groupLabel="IA",
       stateAtRoomTemp="金黄色固态金属（熔点 28.44°C，近室温）", density="1.873 g/cm³",
       meltingPoint=28.44, boilingPoint=671, electronegativity=0.79,
       electronConfiguration="[Xe] 6s¹", oxidationStates="+1",
       chemicalProperties="铯是电负性最低的元素（0.79），化学性质极其活泼，在空气中迅速氧化，与水反应会爆炸，甚至能与冰在低温下反应。铯金属呈金黄色，是碱金属中颜色最深的。",
       history="1860 年本生和基尔霍夫用光谱法发现，是第一个通过光谱仪发现的元素。名称来自拉丁语 caesius（天蓝色），因其特征蓝色谱线而得名。",
       applications="铯原子钟（精确计时，秒的定义基于铯-133）、光电管、离子推进器（航天）、钻井液（铯甲酸盐）。",
       funFact="国际单位秒的定义基于铯-133 原子超精细跃迁频率（9,192,631,770 Hz），铯原子钟精度达每 3 亿年误差不超过 1 秒，是人类最精确的计时工具。",
       educationalLinks=["[高中选修] 碱金属活泼性递变的极端"]),

  dict(atomicNumber=56, symbol="Ba", nameZh="钡", nameEn="Barium",
       atomicMass="137.33", category="alkaline-earth-metal", period=6, group=2, groupLabel="IIA",
       stateAtRoomTemp="银白色固态金属", density="3.51 g/cm³",
       meltingPoint=727, boilingPoint=1845, electronegativity=0.89,
       electronConfiguration="[Xe] 6s²", oxidationStates="+2",
       chemicalProperties="钡是活泼碱土金属，与空气、水反应。BaSO₄ 不溶于水和酸，可检验 SO₄²⁻（加稀 HNO₃ 不溶解）。Ba²⁺ 焰色反应为黄绿色。BaCO₃ 有毒，可溶于胃酸。",
       history="1808 年戴维电解熔融氯化钡制得。名称来自希腊语 barys（重），因重晶石（BaSO₄）密度较大。",
       applications="BaSO₄（钡餐，胃肠 X 射线造影）、白色颜料（立德粉）、焰火（黄绿色）、钡基润滑脂。",
       funFact="钡餐检查利用 BaSO₄ 不透 X 射线且无毒（不溶于水和酸）的特性，患者服下钡餐后，胃肠轮廓在 X 光下清晰可见，是临床影像学的经典方法。",
       educationalLinks=["[高中必修] Ba²⁺ 检验 SO₄²⁻"]),

  # ── Lanthanides (period 6, group null) ─────────────────────
  dict(atomicNumber=57, symbol="La", nameZh="镧", nameEn="Lanthanum",
       atomicMass="138.91", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="6.15 g/cm³",
       meltingPoint=920, boilingPoint=3464, electronegativity=1.1,
       electronConfiguration="[Xe] 5d¹ 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1839 年莫桑德尔从铈的化合物中分离，名称来自希腊语 lanthanein（隐藏）。",
       applications="汽车尾气催化剂、高折射率光学玻璃、镍氢电池（LaNi₅ 储氢合金）、镧钴永磁体。",
       funFact="镧系元素之所以化学性质极为相似，是因为 4f 轨道被外层 5s²5p⁶ 电子屏蔽，各元素的外层电子构型几乎相同，导致化学行为高度一致。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=58, symbol="Ce", nameZh="铈", nameEn="Cerium",
       atomicMass="140.12", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="6.77 g/cm³",
       meltingPoint=798, boilingPoint=3443, electronegativity=1.12,
       electronConfiguration="[Xe] 4f¹ 5d¹ 6s²", oxidationStates="+3, +4",
       chemicalProperties="铈是地壳中最丰富的稀土元素。铈具有 +3 和 +4 两种氧化态，Ce⁴⁺ 是强氧化剂。CeO₂ 在高温下可释放和吸收氧，是汽车三元催化剂的关键储氧材料。",
       history="1803 年贝采利乌斯和希辛格尔发现，以小行星谷神星（Ceres）命名。",
       applications="汽车三元催化剂（CeO₂）、玻璃抛光剂（氧化铈粉）、自清洁玻璃、铈钨电极。",
       funFact="铈是稀土元素中地壳丰度最高的，甚至比常见金属锡还丰富。CeO₂ 在催化转化器中扮演储氧库的角色，在富氧和贫氧条件之间动态调节，大幅降低尾气污染。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=59, symbol="Pr", nameZh="镨", nameEn="Praseodymium",
       atomicMass="140.91", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="6.77 g/cm³",
       meltingPoint=931, boilingPoint=3520, electronegativity=1.13,
       electronConfiguration="[Xe] 4f³ 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1885 年冯·威尔斯巴赫从钕镨混合物中分离，名称来自希腊语 prasios（绿色）+ didymos（双胞胎）。",
       applications="钕磁铁（NdFeB 中添加镨以提高矫顽力）、高强度镁合金、飞机发动机叶片合金、镨钕混合滤光玻璃。",
       funFact="镨和钕在名称上有历史渊源——两者曾被误认为是同一种元素（didymium），直到 1885 年冯·威尔斯巴赫才将其分离为绿色的镨和粉红色的钕。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=60, symbol="Nd", nameZh="钕", nameEn="Neodymium",
       atomicMass="144.24", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="7.01 g/cm³",
       meltingPoint=1021, boilingPoint=3074, electronegativity=1.14,
       electronConfiguration="[Xe] 4f⁴ 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1885 年冯·威尔斯巴赫从钕镨混合物中分离，名称来自希腊语 neos（新）+ didymos（双胞胎）。",
       applications="NdFeB 钕磁铁（最强永磁体，用于电机、耳机、硬盘驱动器）、钕玻璃激光器、风力发电机。",
       funFact="钕铁硼（NdFeB）磁铁是迄今最强的永磁体——一块鸡蛋大小的钕磁铁能吸住数百公斤重物。现代电动汽车和风力发电机大量依赖钕磁铁。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=61, symbol="Pm", nameZh="钷", nameEn="Promethium",
       atomicMass="145", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="7.26 g/cm³",
       meltingPoint=1042, boilingPoint=3000, electronegativity=1.13,
       electronConfiguration="[Xe] 4f⁵ 6s²", oxidationStates="+3",
       chemicalProperties="钷是镧系中唯一没有稳定同位素的元素，所有同位素均具放射性。化学性质与其他镧系相似，均为 +3 价。",
       history="1945 年马林斯基等人从铀裂变产物中分离，以希腊神话中盗火的普罗米修斯命名。",
       applications="核电池（放射性同位素热电发生器）、早期航天器电源、荧光涂料（历史）。",
       funFact="钷是元素周期表中第 61 号元素，也是原子序数小于 83（铋）的所有元素中唯一没有稳定同位素的一个。地球自然界中不存在钷，全部需人工制备。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=62, symbol="Sm", nameZh="钐", nameEn="Samarium",
       atomicMass="150.36", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="7.52 g/cm³",
       meltingPoint=1072, boilingPoint=1794, electronegativity=1.17,
       electronConfiguration="[Xe] 4f⁶ 6s²", oxidationStates="+2, +3",
       chemicalProperties=LANT_CHEM,
       history="1879 年德马尔克从矿石 samarskite 中分离，以俄国矿业官员萨马尔斯基命名——首个以人名命名的元素。",
       applications="钐钴磁铁（SmCo，耐高温强永磁体）、核反应堆中子吸收体（¹⁴⁹Sm 截面大）、癌症靶向放射治疗。",
       funFact="钐钴（SmCo）磁铁是钕磁铁发明前最强的永磁体，其最大优势是耐温性——在高温（>150°C）和腐蚀环境下仍能保持磁性，广泛用于航空航天电机。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=63, symbol="Eu", nameZh="铕", nameEn="Europium",
       atomicMass="151.96", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="5.24 g/cm³",
       meltingPoint=822, boilingPoint=1529, electronegativity=1.2,
       electronConfiguration="[Xe] 4f⁷ 6s²", oxidationStates="+2, +3",
       chemicalProperties="铕在镧系中化学活泼性较强，能以 +2 和 +3 两种氧化态稳定存在（Eu²⁺ 类似 Sr²⁺）。铕的荧光性质使其成为重要的发光材料。",
       history="1901 年德马尔克分离，以欧洲（Europe）命名。",
       applications="红色荧光粉（Eu³⁺ 发红光，用于 LED、液晶背光）、防伪荧光标记（欧元纸币）、彩色电视显像管红色荧光体。",
       funFact="欧元纸币中含有铕荧光防伪标记——在紫外光照射下会发出特征红色荧光。铕是彩色显示技术的重要组成部分，使我们看到的屏幕红色更纯正。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=64, symbol="Gd", nameZh="钆", nameEn="Gadolinium",
       atomicMass="157.25", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="7.90 g/cm³",
       meltingPoint=1312, boilingPoint=3273, electronegativity=1.2,
       electronConfiguration="[Xe] 4f⁷ 5d¹ 6s²", oxidationStates="+3",
       chemicalProperties="钆的热中子吸收截面是已知最大的（49000 barn），远超铀和钚。钆具有异常强的顺磁性，可作为 MRI 造影剂。",
       history="1880 年马里尼亚克从钐矿中分离，以芬兰矿物学家加多林命名。",
       applications="MRI 造影剂（Gd-DTPA 螯合物，增强血管和组织对比）、核反应堆中子吸收体、磁制冷材料。",
       funFact="钆是 MRI 检查中最常用的造影剂成分——钆的七个未成对电子使其顺磁性极强，能显著缩短附近水分子的弛豫时间，令病灶在核磁共振图像中亮度突出。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=65, symbol="Tb", nameZh="铽", nameEn="Terbium",
       atomicMass="158.93", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="8.23 g/cm³",
       meltingPoint=1356, boilingPoint=3230, electronegativity=1.2,
       electronConfiguration="[Xe] 4f⁹ 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1843 年莫桑德尔从钇矿中分离，以瑞典村庄伊特比（Ytterby）命名。",
       applications="绿色荧光粉（Tb³⁺ 发绿光，LED 照明）、Terfenol-D 磁致伸缩材料（声纳、精密驱动器）、固体氧化物燃料电池。",
       funFact="铽是磁致伸缩材料 Terfenol-D（铽-铁-镝合金）的核心成分——该材料在磁场中发生形变，可将电磁信号转换为机械振动，广泛用于声纳和超精密定位系统。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=66, symbol="Dy", nameZh="镝", nameEn="Dysprosium",
       atomicMass="162.50", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="8.55 g/cm³",
       meltingPoint=1412, boilingPoint=2567, electronegativity=1.22,
       electronConfiguration="[Xe] 4f¹⁰ 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1886 年德马尔克分离，名称来自希腊语 dysprositos（难以得到）。",
       applications="钕铁硼磁铁添加剂（提高高温矫顽力）、中子吸收体、激光材料。",
       funFact="镝是电动汽车钕铁硼磁铁的重要添加剂——在磁铁中加入少量镝（约 1%）可使磁铁在高温下（如电机工作温度）保持强磁性，使电动汽车更高效可靠。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=67, symbol="Ho", nameZh="钬", nameEn="Holmium",
       atomicMass="164.93", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="8.80 g/cm³",
       meltingPoint=1474, boilingPoint=2700, electronegativity=1.23,
       electronConfiguration="[Xe] 4f¹¹ 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1878 年克利夫分离，以斯德哥尔摩的拉丁语名 Holmia 命名。",
       applications="钬激光（Ho:YAG，用于泌尿外科碎石和骨科手术）、磁场调节器（钬磁通量集中器）。",
       funFact="钬激光（Ho:YAG 激光）是泌尿外科的重要工具，能在体内将肾结石击碎成粉末状，无需开刀，已成为腔镜碎石的标准手段。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=68, symbol="Er", nameZh="铒", nameEn="Erbium",
       atomicMass="167.26", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="9.07 g/cm³",
       meltingPoint=1529, boilingPoint=2868, electronegativity=1.24,
       electronConfiguration="[Xe] 4f¹² 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1843 年莫桑德尔从钇矿中分离，以伊特比（Ytterby）命名。",
       applications="铒掺杂光纤放大器（EDFA，现代互联网光通信核心器件）、皮肤激光美容（Er:YAG）、粉红色玻璃着色。",
       funFact="全球互联网骨干网的光信号传输依赖铒——铒掺杂光纤放大器（EDFA）能在不转换为电信号的情况下直接放大 1550 nm 光信号，使光纤通信传输距离突破数千公里。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=69, symbol="Tm", nameZh="铥", nameEn="Thulium",
       atomicMass="168.93", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="9.32 g/cm³",
       meltingPoint=1545, boilingPoint=1950, electronegativity=1.25,
       electronConfiguration="[Xe] 4f¹³ 6s²", oxidationStates="+3",
       chemicalProperties=LANT_CHEM,
       history="1879 年克利夫分离，以传说中斯堪的纳维亚的古地名 Thule 命名。",
       applications="便携式 X 射线源（¹⁷⁰Tm 放射性同位素）、铥激光（2 μm 波段，外科和激光雷达）。",
       funFact="铥是镧系元素中最稀少且最昂贵的之一。放射性同位素 ¹⁷⁰Tm 可用作小型 X 射线源，无需电力即可拍摄 X 光片，适合野外无电力的医疗诊断。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=70, symbol="Yb", nameZh="镱", nameEn="Ytterbium",
       atomicMass="173.04", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="6.90 g/cm³",
       meltingPoint=824, boilingPoint=1196, electronegativity=1.1,
       electronConfiguration="[Xe] 4f¹⁴ 6s²", oxidationStates="+2, +3",
       chemicalProperties="镱的 4f 轨道已填满，在化学性质上与其他镧系略有不同，可以 +2 价（类似碱土金属）稳定存在。",
       history="1878 年马里尼亚克从钇矿中分离，以伊特比（Ytterby）命名——该村矿山共贡献了 4 个元素的发现。",
       applications="镱光纤激光器（Yb:fiber，1 μm 波段，工业激光加工）、镱原子钟（精度超过铯原子钟）、应力测量（镱压阻传感器）。",
       funFact="镱原子钟的精度已超过铯原子钟，成为新一代时间标准的候选者——基于光频跃迁的镱光钟每 140 亿年误差不超过 1 秒，精度是铯钟的 1000 倍。",
       educationalLinks=LANT_EDU),

  dict(atomicNumber=71, symbol="Lu", nameZh="镥", nameEn="Lutetium",
       atomicMass="174.97", category="lanthanide", period=6, group=None, groupLabel="镧系",
       stateAtRoomTemp="银白色固态金属", density="9.84 g/cm³",
       meltingPoint=1663, boilingPoint=3402, electronegativity=1.27,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹ 6s²", oxidationStates="+3",
       chemicalProperties="镥是镧系的最后一个元素，4f 轨道完全填充。由于镧系收缩，镥的离子半径最小，在许多催化和医疗应用中表现突出。",
       history="1907 年韦尔斯巴赫和于尔班独立分离，以巴黎的拉丁语名 Lutetia 命名。",
       applications="PET 扫描仪探测器晶体（Lu₂SiO₅:Ce，LSO）、癌症放射治疗（¹⁷⁷Lu 标记药物）、石油裂化催化剂。",
       funFact="医用同位素 ¹⁷⁷Lu 是肿瘤靶向放射治疗的新星——将 ¹⁷⁷Lu 标记到能与肿瘤受体结合的分子上，可将放射线精确投递到癌细胞，最大限度减少对正常组织的损伤。",
       educationalLinks=LANT_EDU),

  # ── Period 6, d-block and p-block ──────────────────────────
  dict(atomicNumber=72, symbol="Hf", nameZh="铪", nameEn="Hafnium",
       atomicMass="178.49", category="transition-metal", period=6, group=4, groupLabel="IVB",
       stateAtRoomTemp="银灰色固态金属", density="13.31 g/cm³",
       meltingPoint=2233, boilingPoint=4603, electronegativity=1.3,
       electronConfiguration="[Xe] 4f¹⁴ 5d² 6s²", oxidationStates="+4",
       chemicalProperties="铪与锆化学性质极为相似（镧系收缩导致），但中子吸收截面大（102 barn 对比锆的 0.18 barn），因此在核工业中扮演相反的角色。",
       history="1923 年科斯特和德海韦西在哥本哈根用 X 射线光谱法发现，以哥本哈根的拉丁语名 Hafnia 命名。",
       applications="核反应堆控制棒（高热中子吸收截面）、高介电常数栅极介质（HfO₂，先进芯片）、航空发动机高温合金。",
       funFact="铪与锆几乎无法通过化学方法分离（镧系收缩导致性质极度相近），却在核工业中用途截然相反——锆用于核燃料包壳（透明于中子），铪用于控制棒（强烈吸收中子）。",
       educationalLinks=["[拓展] 镧系收缩的实际应用"]),

  dict(atomicNumber=73, symbol="Ta", nameZh="钽", nameEn="Tantalum",
       atomicMass="180.95", category="transition-metal", period=6, group=5, groupLabel="VB",
       stateAtRoomTemp="蓝灰色固态金属", density="16.65 g/cm³",
       meltingPoint=3017, boilingPoint=5458, electronegativity=1.5,
       electronConfiguration="[Xe] 4f¹⁴ 5d³ 6s²", oxidationStates="+5",
       chemicalProperties="钽耐腐蚀性极强（仅次于铂和铱），常温下表面形成致密的 Ta₂O₅ 氧化膜。钽不溶于盐酸、硝酸、甚至王水，仅溶于氢氟酸。",
       history="1802 年埃克贝格发现，以希腊神话中受罚的坦塔罗斯命名——因其不溶于大多数酸，如同坦塔罗斯在水中无法饮水。",
       applications="钽电容器（手机、电脑中的滤波器）、外科植入物（人工关节、颅骨修复）、化学工业耐腐蚀设备。",
       funFact="每部智能手机中都有钽——手机主板上密密麻麻的钽电容提供稳定的电源滤波，钽电容体积小、容量大、性能稳定，是现代电子设备不可或缺的元件。",
       educationalLinks=[]),

  dict(atomicNumber=74, symbol="W", nameZh="钨", nameEn="Tungsten",
       atomicMass="183.84", category="transition-metal", period=6, group=6, groupLabel="VIB",
       stateAtRoomTemp="银灰色固态金属", density="19.25 g/cm³",
       meltingPoint=3422, boilingPoint=5555, electronegativity=2.36,
       electronConfiguration="[Xe] 4f¹⁴ 5d⁴ 6s²", oxidationStates="+6",
       chemicalProperties="钨的熔点是所有金属中最高的（3422°C），沸点也最高（5555°C）。钨的电阻率随温度升高而增大，是白炽灯工作原理的基础。碳化钨（WC）硬度仅次于金刚石。",
       history="1783 年胡安和福斯托·埃尔乌亚尔兄弟首先分离，元素符号 W 来自德语 Wolfram（钨矿石名）。",
       applications="白炽灯钨丝、硬质合金切削工具（WC-Co）、穿甲弹（钨合金）、X 射线管靶材、高温炉发热体。",
       funFact="钨的熔点（3422°C）是所有金属中最高的，甚至超过了太阳表面温度的一半。1 克钨可以拉成约 26 公里长的细丝——正是这根细丝，点亮了人类一百多年的夜晚。",
       educationalLinks=["[拓展] 熔点最高的金属"]),

  dict(atomicNumber=75, symbol="Re", nameZh="铼", nameEn="Rhenium",
       atomicMass="186.21", category="transition-metal", period=6, group=7, groupLabel="VIIB",
       stateAtRoomTemp="银白色固态金属", density="21.02 g/cm³",
       meltingPoint=3186, boilingPoint=5596, electronegativity=1.9,
       electronConfiguration="[Xe] 4f¹⁴ 5d⁵ 6s²", oxidationStates="+4, +6, +7",
       chemicalProperties="铼是熔点第二高的金属（3186°C）。铼具有宽范围的氧化态（-1 到 +7）。Re₂O₇ 是强 Lewis 酸，铼催化剂用于石油重整。",
       history="1925 年诺达克夫妇和伯格在铂矿和铌钽矿石中发现，以莱茵河（Rhine）命名，是最后一个发现的稳定元素。",
       applications="喷气发动机单晶叶片高温合金（含铼的镍基合金）、石油催化重整催化剂（Re-Pt/Al₂O₃）、热电偶（钨铼丝）。",
       funFact="铼是地壳中最稀少的稳定元素之一，年产量仅约 50 吨。现代喷气发动机的单晶高温合金叶片中含铼（约 3-6%），使叶片能在超过熔点 85% 的温度下工作。",
       educationalLinks=[]),

  dict(atomicNumber=76, symbol="Os", nameZh="锇", nameEn="Osmium",
       atomicMass="190.23", category="transition-metal", period=6, group=8, groupLabel="VIII族",
       stateAtRoomTemp="蓝灰色固态金属", density="22.59 g/cm³",
       meltingPoint=3033, boilingPoint=5012, electronegativity=2.2,
       electronConfiguration="[Xe] 4f¹⁴ 5d⁶ 6s²", oxidationStates="+4, +8",
       chemicalProperties="锇是密度最大的元素（22.59 g/cm³）。OsO₄ 是挥发性强氧化剂，有强烈刺激性气味，是有机化学中双羟化反应的重要试剂，也用于电镜生物样品染色。",
       history="1803 年坦南特从铂矿残渣中发现，名称来自希腊语 osme（气味），因 OsO₄ 的刺鼻气味。",
       applications="OsO₄（生物电镜染色、有机合成双羟化）、铂铱锇合金（极硬，用于钢笔笔尖、精密仪器轴承）。",
       funFact="锇是地球上密度最大的天然元素（22.59 g/cm³），比铅重约两倍。然而其四氧化物 OsO₄ 在室温下即挥发，刺鼻气味且剧毒——密度最大的元素却有着出乎意料危险的一面。",
       educationalLinks=[]),

  dict(atomicNumber=77, symbol="Ir", nameZh="铱", nameEn="Iridium",
       atomicMass="192.22", category="transition-metal", period=6, group=9, groupLabel="VIII族",
       stateAtRoomTemp="银白色固态金属", density="22.56 g/cm³",
       meltingPoint=2446, boilingPoint=4428, electronegativity=2.2,
       electronConfiguration="[Xe] 4f¹⁴ 5d⁷ 6s²", oxidationStates="+3, +4",
       chemicalProperties="铱是耐腐蚀性最强的金属，在高温下仍能抵抗强酸腐蚀。铱不溶于王水，仅溶于熔融盐。铱合金极为坚硬，是最硬的铂族金属。",
       history="1803 年坦南特从铂矿残渣中发现，名称来自希腊语 iris（彩虹），因其盐类色彩丰富。",
       applications="铂铱合金（国际千克原器、标准米尺，现已退役）、火花塞铱合金电极、铱坩埚（高温生长氧化物晶体）。",
       funFact="白垩纪-古近纪地层中存在一层薄薄的铱异常层，铱含量是正常地壳的 30-160 倍。由于铱在地外陨石中含量远高于地壳，这被认为是 6600 万年前小行星撞击地球、导致恐龙灭绝的关键证据。",
       educationalLinks=[]),

  dict(atomicNumber=78, symbol="Pt", nameZh="铂", nameEn="Platinum",
       atomicMass="195.08", category="transition-metal", period=6, group=10, groupLabel="VIII族",
       stateAtRoomTemp="银白色固态金属", density="21.45 g/cm³",
       meltingPoint=1768, boilingPoint=3825, electronegativity=2.28,
       electronConfiguration="[Xe] 4f¹⁴ 5d⁹ 6s¹", oxidationStates="+2, +4",
       chemicalProperties="铂是贵金属中最重要的催化剂。铂不溶于单一酸（包括浓 HNO₃），仅溶于王水（浓 HCl + 浓 HNO₃ = 3:1）。铂对 H₂、O₂、CO 等气体有强吸附催化能力。",
       history="南美洲原住民曾使用天然铂金。18 世纪欧洲科学家系统研究，名称来自西班牙语 platina（小银子）。",
       applications="汽车三元催化转化器（Pt/Pd/Rh）、燃料电池催化剂（铂碳）、石化催化重整、铂金珠宝、顺铂（抗癌药）。",
       funFact="全球约 40% 的铂用于汽车尾气催化转化器，将有毒的 CO 和 NOₓ 转化为无害的 CO₂ 和 N₂。一辆现代汽车的三元催化器中大约含有 3-7 克铂族金属。",
       educationalLinks=["[高中选修] 王水溶解 Au/Pt；燃料电池催化剂"]),

  dict(atomicNumber=79, symbol="Au", nameZh="金", nameEn="Gold",
       atomicMass="196.97", category="transition-metal", period=6, group=11, groupLabel="IB",
       stateAtRoomTemp="金黄色固态金属", density="19.32 g/cm³",
       meltingPoint=1064, boilingPoint=2856, electronegativity=2.54,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s¹", oxidationStates="+1, +3",
       chemicalProperties="金是化学稳定性最强的金属之一，在自然界以单质存在。金不溶于任何单一酸，仅溶于王水（3HCl + HNO₃）。金的延展性极好——1 克金可拉成 3000 米金丝，或锤成 0.5 m² 金箔。",
       history="人类最早使用的金属之一，在古埃及、中国、美索不达米亚等文明中均有数千年使用历史。元素符号 Au 来自拉丁语 aurum。",
       applications="珠宝货币、电子设备金触点（高导电性和抗氧化）、牙科材料、纳米金颗粒（医学诊断）、顺铂类抗癌药物前体。",
       funFact="纳米金颗粒并非金黄色，而是红色、橙色或紫色——颗粒尺寸决定其颜色，因为不同粒径对光的等离子共振吸收波长不同。中世纪教堂彩色玻璃的红色正是来自玻璃中的纳米金颗粒。",
       educationalLinks=["[高中选修] 王水溶解金、胶体知识"]),

  dict(atomicNumber=80, symbol="Hg", nameZh="汞", nameEn="Mercury",
       atomicMass="200.59", category="transition-metal", period=6, group=12, groupLabel="IIB",
       stateAtRoomTemp="液态金属（常温下唯一液态金属）", density="13.53 g/cm³",
       meltingPoint=-38.83, boilingPoint=356.73, electronegativity=2.0,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s²", oxidationStates="+1, +2",
       chemicalProperties="汞是常温下唯一的液态金属（熔点-38.83°C）。汞蒸气有毒，有机汞（甲基汞）毒性更强。汞能溶解许多金属形成汞齐。汞不与稀酸反应，与浓 HNO₃ 反应生成 Hg(NO₃)₂。",
       history="人类使用汞有数千年历史。中国古代称水银，认为有长生功效。名称 Mercury 来自罗马神墨丘利，元素符号 Hg 来自拉丁语 hydrargyrum（液态银）。",
       applications="温度计（正在淘汰）、气压计、荧光灯（汞蒸气放电）、氯碱工业（汞电极，已逐步淘汰）、牙科汞合金。",
       funFact="日本水俣病是 20 世纪最严重的公害事件之一——化工厂将含汞废水排入水俣湾，汞在食物链中富集为甲基汞，渔民长期食用受污染的鱼后出现严重神经系统损伤，揭示了重金属污染的可怕危害。",
       educationalLinks=["[初中] 温度计中的汞", "[高中选修] 重金属污染"]),

  dict(atomicNumber=81, symbol="Tl", nameZh="铊", nameEn="Thallium",
       atomicMass="204.38", category="post-transition-metal", period=6, group=13, groupLabel="IIIA",
       stateAtRoomTemp="银白色固态金属", density="11.85 g/cm³",
       meltingPoint=304, boilingPoint=1473, electronegativity=1.62,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹", oxidationStates="+1, +3",
       chemicalProperties="铊是剧毒重金属，Tl⁺ 离子与 K⁺ 尺寸相近，能欺骗生物体的钾通道，干扰神经传导。铊的化合物无色无味，难以察觉。",
       history="1861 年克鲁克斯用光谱法发现，名称来自希腊语 thallos（绿枝），因其特征绿色谱线。",
       applications="CdZnTe 核辐射探测器（掺铊）、心脏核医学成像（²⁰¹Tl）、红外光学玻璃（KRS-5 晶体）。",
       funFact="铊盐曾被用作毒鼠药（无色无味，低剂量即致死），因其极易被人误用，大多数国家已全面禁止。铊中毒最典型的症状是头发全部脱落，被称为重金属毒物中的隐形杀手。",
       educationalLinks=[]),

  dict(atomicNumber=82, symbol="Pb", nameZh="铅", nameEn="Lead",
       atomicMass="207.2", category="post-transition-metal", period=6, group=14, groupLabel="IVA",
       stateAtRoomTemp="蓝灰色固态金属", density="11.34 g/cm³",
       meltingPoint=327.46, boilingPoint=1749, electronegativity=2.33,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²", oxidationStates="+2, +4",
       chemicalProperties="铅是质软、密度大的重金属。铅的 6s² 孤对电子效应（惰性电子对效应）使 +2 价更稳定。铅对 X 射线和 γ 射线有很强的屏蔽作用。PbSO₄ 和 PbO₂ 是铅蓄电池的关键材料。",
       history="人类最早使用的金属之一，古罗马广泛用铅制水管和酒器（铅中毒可能影响了罗马帝国的命运）。元素符号 Pb 来自拉丁语 plumbum。",
       applications="铅蓄电池（汽车启动电池）、辐射防护（X 射线/γ 射线屏蔽）、子弹/弹头、铅玻璃（光学）。",
       funFact="古罗马人用铅锅烹饪、用铅管输水，甚至用含铅的醋酸铅（铅糖）来增甜葡萄酒。历史学家认为慢性铅中毒可能是影响罗马贵族健康和决策的因素之一。",
       educationalLinks=["[高中必修] 铅蓄电池"]),

  dict(atomicNumber=83, symbol="Bi", nameZh="铋", nameEn="Bismuth",
       atomicMass="208.98", category="post-transition-metal", period=6, group=15, groupLabel="VA",
       stateAtRoomTemp="银白色带粉红光泽固体", density="9.78 g/cm³",
       meltingPoint=271.5, boilingPoint=1564, electronegativity=2.02,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³", oxidationStates="+3, +5",
       chemicalProperties="铋是密度最大的稳定无毒金属。铋在凝固时体积膨胀（类似冰），与大多数金属相反。铋的氧化物呈现丰富色彩。",
       history="15 世纪已有记载，长期与铅和锡混淆。名称来源有争议，可能来自德语 Wismut。1753 年热弗鲁瓦证明铋是独立元素。",
       applications="次水杨酸铋（胃药，碧然德）、低熔点合金（Bi-Pb-Sn，保险丝、焊料）、铋黄色颜料（替代有毒铬黄）、热电材料。",
       funFact="铋晶体拥有极为美丽的彩虹色氧化层——由于铋的薄氧化层厚度不均，干涉光形成从金色到蓝紫色的结构色渐变，使每一块铋晶体都像独一无二的彩色宝石。",
       educationalLinks=[]),

  dict(atomicNumber=84, symbol="Po", nameZh="钋", nameEn="Polonium",
       atomicMass="209", category="post-transition-metal", period=6, group=16, groupLabel="VIA",
       stateAtRoomTemp="银白色固态金属（放射性）", density="9.32 g/cm³",
       meltingPoint=254, boilingPoint=962, electronegativity=2.0,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴", oxidationStates="+2, +4",
       chemicalProperties="钋是强放射性元素，主要衰变方式为 α 衰变。²¹⁰Po 的比放射性极高，微克量级即可造成致命辐射剂量。钋产生的辐射热使其表面温度可升至数百度。",
       history="1898 年居里夫妇从沥青铀矿中发现，以居里夫人的祖国波兰（Polonia）命名，是首个以国家命名的元素。",
       applications="静电消除器（²¹⁰Po α 射线电离空气，工业用）、早期核武器点火中子源（钋-铍中子源）。",
       funFact="2006 年前俄罗斯特工亚历山大·利特维年科在伦敦被 ²¹⁰Po 毒杀，这是有记录以来首例使用钋实施谋杀的案件。²¹⁰Po 几乎不发射 γ 射线，难以被常规探测仪发现，是极为隐蔽的毒药。",
       educationalLinks=[]),

  dict(atomicNumber=85, symbol="At", nameZh="砹", nameEn="Astatine",
       atomicMass="210", category="halogen", period=6, group=17, groupLabel="VIIA",
       stateAtRoomTemp="黑色固体（推测，放射性）", density="—",
       meltingPoint=302, boilingPoint=337, electronegativity=2.2,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵", oxidationStates="-1, +1, +3, +5",
       chemicalProperties="砹是最重的卤素，也是自然界最稀少的天然元素。其化学性质推测与碘相似，但金属性更强。由于半衰期极短，其化学性质难以精确研究。",
       history="1940 年科森、麦肯齐和西格雷在伯克利用 α 粒子轰击铋合成，名称来自希腊语 astatos（不稳定）。",
       applications="癌症靶向放射治疗（²¹¹At 标记抗体，α 射线精确杀死肿瘤细胞）。",
       funFact="地球上所有天然砹加在一起，任意时刻的总量不超过 1 克。它是通过铀和钍的天然衰变链微量生成的，但很快又衰变消失。",
       educationalLinks=[]),

  dict(atomicNumber=86, symbol="Rn", nameZh="氡", nameEn="Radon",
       atomicMass="222", category="noble-gas", period=6, group=18, groupLabel="0族",
       stateAtRoomTemp="无色放射性气体", density="9.73 g/L（0°C）",
       meltingPoint=-71, boilingPoint=-61.7, electronegativity=None,
       electronConfiguration="[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶", oxidationStates="0",
       chemicalProperties="氡是唯一天然放射性稀有气体，所有同位素均有放射性。氡由镭衰变产生，α 衰变链中的中间产物。目前已合成少量 RnF₂ 化合物。",
       history="1900 年道恩从镭的衰变产物中发现。1908 年冉姆赛确认为新元素，命名 radium emanation，后简化为 radon。",
       applications="氡疗（历史上争议用法）、物理研究、地震前兆监测（地壳氡释放异常）。",
       funFact="室内氡积累是仅次于吸烟的第二大肺癌诱因。氡从岩石和土壤中渗入地下室，在通风不良的房间中浓缩，长期暴露会显著增加肺癌风险——购买房屋前检测氡浓度已成为许多国家的常规建议。",
       educationalLinks=[]),

  # ── Period 7 ──────────────────────────────────────────────
  dict(atomicNumber=87, symbol="Fr", nameZh="钫", nameEn="Francium",
       atomicMass="223", category="alkali-metal", period=7, group=1, groupLabel="IA",
       stateAtRoomTemp="放射性固态金属（推测）", density="—",
       meltingPoint=27, boilingPoint=677, electronegativity=0.7,
       electronConfiguration="[Rn] 7s¹", oxidationStates="+1",
       chemicalProperties="钫是最不稳定的天然碱金属，最长寿命同位素 ²²³Fr 半衰期仅 22 分钟。理论上应是活泼性最强的碱金属，但因数量极少，其化学性质几乎无法直接研究。",
       history="1939 年法国物理学家玛格丽特·佩雷在放射性衰变产物中发现，以法国（France）命名——也是最后一个被发现的天然元素。",
       applications="基础物理研究（激光冷却钫原子测量弱相互作用）。",
       funFact="钫是人类发现的最后一个天然存在的元素（1939 年）。地球上任意时刻自然存在的钫总量估计不超过 30 克——全部来自铀和钍的衰变链，且不断生成又不断衰变。",
       educationalLinks=[]),

  dict(atomicNumber=88, symbol="Ra", nameZh="镭", nameEn="Radium",
       atomicMass="226", category="alkaline-earth-metal", period=7, group=2, groupLabel="IIA",
       stateAtRoomTemp="银白色固态金属（放射性）", density="5.0 g/cm³",
       meltingPoint=700, boilingPoint=1737, electronegativity=0.9,
       electronConfiguration="[Rn] 7s²", oxidationStates="+2",
       chemicalProperties="镭是放射性最强的天然元素之一，α/β/γ 射线俱全。镭的放射性热量使其在黑暗中发出蓝色荧光。化学性质类似钡，BaSO₄ 共沉淀法可从矿石中富集镭。",
       history="1898 年居里夫妇从沥青铀矿中发现，名称来自拉丁语 radius（射线）。居里夫人因研究放射性两度获诺贝尔奖，是唯一获得两个不同学科诺贝尔奖的科学家。",
       applications="早期放射治疗（肿瘤，已被更安全的同位素取代）、早期钟表和仪表夜光涂料（已禁止）。",
       funFact="早期镭被宣传为包治百病的神奇物质——添加镭的饮用水、牙膏、化妆品甚至巧克力曾风靡一时。20 世纪初的表盘女工因用嘴舔笔尖涂镭发光漆而患颌骨坏死和白血病，其诉讼案成为工人安全权益的历史里程碑。",
       educationalLinks=["[高中选修] 放射性发现史"]),

  # ── Actinides (period 7, group null) ───────────────────────
  dict(atomicNumber=89, symbol="Ac", nameZh="锕", nameEn="Actinium",
       atomicMass="227", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="10.07 g/cm³",
       meltingPoint=1050, boilingPoint=3200, electronegativity=1.1,
       electronConfiguration="[Rn] 6d¹ 7s²", oxidationStates="+3",
       chemicalProperties="锕是锕系之首，化学性质与镧相似，主要以 +3 价存在。锕的放射性较强，发出蓝色辉光（切伦科夫辐射）。",
       history="1899 年德比耶纳从沥青铀矿中发现，名称来自希腊语 aktis（射线）。",
       applications="²²⁷Ac 中子源、²²⁵Ac 靶向 α 治疗癌症（新型放射性药物）。",
       funFact="锕在黑暗中发出幽蓝色辉光——这不是荧光，而是其放射性衰变粒子使周围空气电离发光的切伦科夫辐射，就像核反应堆水池中著名的蓝色光晕。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=90, symbol="Th", nameZh="钍", nameEn="Thorium",
       atomicMass="232.04", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="11.72 g/cm³",
       meltingPoint=1750, boilingPoint=4788, electronegativity=1.3,
       electronConfiguration="[Rn] 6d² 7s²", oxidationStates="+4",
       chemicalProperties="钍是地壳中最丰富的锕系元素，比铀丰度高约 3 倍。²³²Th 是可增殖核材料，在快中子反应堆中可转化为 ²³³U（可裂变）。",
       history="1829 年贝采利乌斯发现，以北欧战神托尔（Thor）命名。",
       applications="钍基核燃料循环（研究阶段）、高温气体冷却堆燃料、氧化钍高强度耐火材料、钨钍合金电极。",
       funFact="钍的地球储量约是铀的 3 倍，且钍反应堆产生的核废料量更少、半衰期更短，被视为未来核能的重要方向。印度因拥有大量钍矿，正积极推进钍基核燃料研究。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=91, symbol="Pa", nameZh="镤", nameEn="Protactinium",
       atomicMass="231.04", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="15.37 g/cm³",
       meltingPoint=1568, boilingPoint=4027, electronegativity=1.5,
       electronConfiguration="[Rn] 5f² 6d¹ 7s²", oxidationStates="+4, +5",
       chemicalProperties="镤是锕衰变链的一部分，²³¹Pa 是 ²³⁵U 衰变系中的成员。高毒性，放射性强，无实际工业用途。",
       history="1917 年迈特纳和哈恩、索迪和克兰斯顿分别独立发现。名称来自希腊语 protos（第一）+ actinium，意为锕的前体。",
       applications="地质年代学（²³¹Pa/²³⁰Th 比值测定古海洋流速）、基础核物理研究。",
       funFact="镤是极为稀少且剧毒的元素，全球总积累量不超过 125 克（用于核研究）。其名称意为锕的前身，因为 ²³¹Pa 通过 α 衰变生成 ²²⁷Ac。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=92, symbol="U", nameZh="铀", nameEn="Uranium",
       atomicMass="238.03", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银灰色固态金属（放射性）", density="18.95 g/cm³",
       meltingPoint=1132, boilingPoint=4131, electronegativity=1.38,
       electronConfiguration="[Rn] 5f³ 6d¹ 7s²", oxidationStates="+4, +6",
       chemicalProperties="天然铀含 ²³⁵U（0.72%，可裂变）和 ²³⁸U（99.27%）。²³⁵U 吸收热中子发生链式裂变反应，释放巨大能量。铀的化学活泼性高，在空气中慢慢氧化，与酸反应。",
       history="1789 年克拉普罗特从沥青铀矿中发现，以天王星（Uranus）命名。1938 年哈恩、迈特纳和斯特拉斯曼发现核裂变。",
       applications="核电站燃料（低浓缩铀，²³⁵U 3-5%）、核武器（高浓缩铀，²³⁵U >90%）、贫铀穿甲弹（²³⁸U，密度极大）。",
       funFact="核裂变链式反应：一个 ²³⁵U 核分裂释放约 200 MeV 能量——1 千克铀裂变释放的能量相当于燃烧约 3000 吨煤。全球 10% 以上的电力来自铀裂变，是现实中最密集的能量来源之一。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=93, symbol="Np", nameZh="镎", nameEn="Neptunium",
       atomicMass="237", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="20.45 g/cm³",
       meltingPoint=644, boilingPoint=3902, electronegativity=1.36,
       electronConfiguration="[Rn] 5f⁴ 6d¹ 7s²", oxidationStates="+4, +5",
       chemicalProperties="镎是第一个超铀元素，由人工核反应制备。化学性质与铀相近，可形成 +3 到 +7 多种氧化态，其中 +5 最稳定。",
       history="1940 年麦克米伦和阿贝尔森在伯克利用中子轰击铀制备，以海王星（Neptune）命名——铀以天王星命名，故下一个以海王星命名。",
       applications="²³⁷Np 可转化为 ²³⁸Pu（用于放射性同位素热电发生器的燃料）、中子探测器。",
       funFact="镎是人类合成的第一个超铀元素，开启了人工制造新元素的时代。²³⁷Np 是核废料的重要成分之一，其半衰期约 214 万年，是长期核废料管理的挑战之一。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=94, symbol="Pu", nameZh="钚", nameEn="Plutonium",
       atomicMass="244", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="19.84 g/cm³",
       meltingPoint=640, boilingPoint=3228, electronegativity=1.28,
       electronConfiguration="[Rn] 5f⁶ 7s²", oxidationStates="+3, +4",
       chemicalProperties="²³⁹Pu 是可裂变材料，在反应堆中由 ²³⁸U 吸收中子后生成。钚化学活泼，具有 +3 到 +7 多种氧化态，在溶液中可同时呈现 4 种氧化态（罕见）。",
       history="1940 年西博格、麦克米伦等人合成，以冥王星（Pluto）命名。曼哈顿计划中大规模生产用于原子弹。",
       applications="核武器弹芯（²³⁹Pu）、核反应堆燃料（MOX 混合氧化物燃料）、深空探测器电源（²³⁸Pu 放射性同位素热电发生器，如旅行者号、卡西尼号）。",
       funFact="旅行者 1 号、好奇号火星车等深空探测器的能源来自 ²³⁸Pu——每克 ²³⁸Pu 衰变释放约 0.57 瓦热量，这种长寿命且稳定的能量来源使探测器能在远离太阳、无法使用太阳能板的地方工作数十年。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=95, symbol="Am", nameZh="镅", nameEn="Americium",
       atomicMass="243", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="13.67 g/cm³",
       meltingPoint=1176, boilingPoint=2607, electronegativity=1.3,
       electronConfiguration="[Rn] 5f⁷ 7s²", oxidationStates="+3",
       chemicalProperties="镅是较常见的超铀元素，可在核反应堆中由钚吸收中子后大量生成。²⁴¹Am 发射 α 射线和低能 γ 射线，化学性质与稀土相似。",
       history="1944 年西博格等人在芝加哥冶金实验室合成，以美洲（Americas）命名。",
       applications="家用烟雾探测器（²⁴¹Am α 射线电离空气，烟雾阻断电离电流即触发报警）、工业厚度测量。",
       funFact="几乎每个家庭都有含镅的设备——普通烟雾探测器中装有约 0.9 微克 ²⁴¹Am，其 α 射线电离空气形成微小电流，当烟雾进入电离室时阻断电流，触发报警，每年拯救无数生命。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=96, symbol="Cm", nameZh="锔", nameEn="Curium",
       atomicMass="247", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="银白色固态金属（放射性）", density="13.51 g/cm³",
       meltingPoint=1340, boilingPoint=3110, electronegativity=1.3,
       electronConfiguration="[Rn] 5f⁷ 6d¹ 7s²", oxidationStates="+3",
       chemicalProperties="锔与钆（64）类似，4f⁷/5f⁷ 半充满构型赋予其特殊稳定性，主要以 +3 价存在。放射性较强，操作需特殊防护。",
       history="1944 年西博格和吉奥尔索等人合成，以居里夫妇（Pierre 和 Marie Curie）命名，以表彰其对放射性研究的伟大贡献。",
       applications="²⁴⁴Cm α 源（用于 α 粒子 X 射线荧光光谱仪，如火星探测器）、核电池。",
       funFact="好奇号火星车上搭载了含锔的仪器 APXS（α 粒子 X 射线光谱仪），利用 ²⁴⁴Cm 的 α 射线照射岩石，通过分析反射 X 射线来确定火星岩石的元素组成。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=97, symbol="Bk", nameZh="锫", nameEn="Berkelium",
       atomicMass="247", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="放射性固态金属（推测）", density="14.78 g/cm³",
       meltingPoint=986, boilingPoint=2627, electronegativity=1.3,
       electronConfiguration="[Rn] 5f⁹ 7s²", oxidationStates="+3",
       chemicalProperties="锫化学性质与镅、锔相似，主要以 +3 价存在。因产量极微，化学研究非常有限。",
       history="1949 年汤普森、吉奥尔索和西博格在伯克利合成，以发现地伯克利（Berkeley）命名。",
       applications="用于合成更重的超铀元素（锫-249 靶材用于合成元素 97 以后的元素）。",
       funFact="锫-249 是合成超重元素的重要靶材——2010 年合成第 117 号元素（鿬）时，用 ²⁴⁹Bk 靶被钙-48 离子轰击，制备了仅约 13 毫克的锫-249 就花费了多年时间。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=98, symbol="Cf", nameZh="锎", nameEn="Californium",
       atomicMass="251", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="放射性固态金属（推测）", density="15.1 g/cm³",
       meltingPoint=900, boilingPoint=1745, electronegativity=1.3,
       electronConfiguration="[Rn] 5f¹⁰ 7s²", oxidationStates="+3",
       chemicalProperties="锎是少数有实际工业应用的超铀元素，²⁵²Cf 每分钟自发裂变释放大量中子（约 2.3×10¹² 中子/克·秒）。",
       history="1950 年汤普森等人在加州大学伯克利分校合成，以加利福尼亚州（California）命名。",
       applications="中子源（启动核反应堆、石油井测井、癌症硼中子俘获治疗）、金属探测（中子活化分析）。",
       funFact="²⁵²Cf 是世界上最昂贵的物质之一，价格约每微克 2700 美元（约每克 27 亿美元）。其强中子发射能力使其成为唯一可实际商业使用的超铀元素。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=99, symbol="Es", nameZh="锿", nameEn="Einsteinium",
       atomicMass="252", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="放射性固态金属（推测）", density="8.84 g/cm³",
       meltingPoint=860, boilingPoint=996, electronegativity=1.3,
       electronConfiguration="[Rn] 5f¹¹ 7s²", oxidationStates="+3",
       chemicalProperties="锿以 +3 价为主，可在溶液中研究其化学性质，但产量极微（微克级）。",
       history="1952 年美国科学家在第一颗氢弹（常青藤麦克）爆炸的放射性尘降物中发现，以爱因斯坦（Einstein）命名。发现消息保密数年。",
       applications="基础核科学研究，用于合成更重的超铀元素。",
       funFact="锿是在氢弹爆炸的灰烬中被发现的——1952 年常青藤麦克氢弹试验后，科学家从放射性尘降物中秘密分离出锿和镄，相关研究保密了数年才公开。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=100, symbol="Fm", nameZh="镄", nameEn="Fermium",
       atomicMass="257", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="放射性固态金属（推测）", density="—",
       meltingPoint=1527, boilingPoint=0, electronegativity=1.3,
       electronConfiguration="[Rn] 5f¹² 7s²", oxidationStates="+3",
       chemicalProperties="镄同样在氢弹爆炸尘降物中发现。因产量极微（皮克级），几乎所有性质均为理论预测。",
       history="1952 年与锿同时在氢弹爆炸尘降物中发现，以恩里科·费米（Enrico Fermi）命名。",
       applications="目前仅用于基础核物理研究。",
       funFact="镄是最后一个可通过中子俘获从宏观量铀/钚出发合成的元素——101 号以后的元素必须用粒子加速器轰击重核才能合成，每次只能产生极少数原子，无法积累宏观量。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=101, symbol="Md", nameZh="钔", nameEn="Mendelevium",
       atomicMass="258", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="放射性固态金属（推测）", density="—",
       meltingPoint=827, boilingPoint=0, electronegativity=1.3,
       electronConfiguration="[Rn] 5f¹³ 7s²", oxidationStates="+3",
       chemicalProperties="钔是首个用加速器离子轰击（而非中子俘获）合成的元素。每次实验仅产生约 1-3 个钔原子，性质极难研究。",
       history="1955 年吉奥尔索等人用氦核轰击锿合成，以门捷列夫（Mendeleev）命名，以表彰其创建元素周期表的伟大贡献。",
       applications="基础核物理研究。",
       funFact="钔是以门捷列夫命名的元素——正是门捷列夫于 1869 年创建的元素周期表预言了未知元素的存在，指导了后来所有元素的发现，这个以他名字命名的元素是对其科学遗产的致敬。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=102, symbol="No", nameZh="锘", nameEn="Nobelium",
       atomicMass="259", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="放射性固态金属（推测）", density="—",
       meltingPoint=827, boilingPoint=0, electronegativity=1.3,
       electronConfiguration="[Rn] 5f¹⁴ 7s²", oxidationStates="+2, +3",
       chemicalProperties="锘在镧系/锕系中较特殊，+2 价（5f¹⁴ 全充满稳定）与 +3 价竞争，在稀土化学中 Md²⁺ 和 No²⁺ 具有特殊意义。",
       history="1958 年苏联杜布纳实验室和美国伯克利实验室分别声称发现，以阿尔弗雷德·诺贝尔（Nobel）命名。",
       applications="基础核物理研究。",
       funFact="锘的命名曾引发国际争议——苏联和美国科学家都声称优先发现权，争执持续多年，最终 IUPAC 于 1994 年正式裁定该元素以诺贝尔命名。",
       educationalLinks=ACT_EDU),

  dict(atomicNumber=103, symbol="Lr", nameZh="铹", nameEn="Lawrencium",
       atomicMass="262", category="actinide", period=7, group=None, groupLabel="锕系",
       stateAtRoomTemp="放射性固态金属（推测）", density="—",
       meltingPoint=1627, boilingPoint=0, electronegativity=1.3,
       electronConfiguration="[Rn] 5f¹⁴ 7s² 7p¹", oxidationStates="+3",
       chemicalProperties="铹是锕系的最后一个元素，5f 轨道完全填充。理论预测其 7p¹ 外层电子使其性质偏离典型锕系规律。",
       history="1961 年吉奥尔索等人在伯克利用硼轰击锎合成，以欧内斯特·劳伦斯（E.O. Lawrence，回旋加速器发明者）命名。",
       applications="基础核物理研究。",
       funFact="铹是锕系元素的最后一个，也是 f 区元素的终结。从 57 号镧到 103 号铹，这 32 个 f 区元素跨越两排，象征着量子力学对元素化学的深刻描述——每一行对应一组角动量量子数 l=3 的 f 轨道填充。",
       educationalLinks=ACT_EDU),

  # ── Period 7 d-block: 超重元素 104-112 ────────────────────
  dict(atomicNumber=104, symbol="Rf", nameZh="𨧀", nameEn="Rutherfordium",
       atomicMass="267", category="transition-metal", period=7, group=4, groupLabel="IVB",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d² 7s²", oxidationStates="+4",
       chemicalProperties="超重过渡金属，理论上应与铪化学性质相似（同族）。已进行少量化学实验，证实其 +4 氧化态。",
       history="1964 年苏联杜布纳实验室和 1969 年美国伯克利实验室分别合成，1997 年 IUPAC 正式命名，以欧内斯特·卢瑟福命名。",
       applications="基础核物理研究，无实际应用。",
       funFact="从 104 号元素起，所有元素均为人工合成，半衰期从毫秒到几分钟不等。它们通过重离子加速器将较轻的核撞击在一起产生，每次实验可能只产生几个原子。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=105, symbol="Db", nameZh="𨭎", nameEn="Dubnium",
       atomicMass="268", category="transition-metal", period=7, group=5, groupLabel="VB",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d³ 7s²", oxidationStates="+5",
       chemicalProperties="理论上应与钽（同族）化学性质相似，已证实其 +5 氧化态。",
       history="1968 年苏联杜布纳实验室和 1970 年美国伯克利合成，1997 年 IUPAC 以俄罗斯杜布纳（Dubna）命名。",
       applications="基础核物理研究。",
       funFact="杜布纳是俄罗斯核物理研究中心所在地，苏联和美国科学家在冷战期间竞相合成超重元素，这场竞争被称为超重元素的发现之争，最终由 IUPAC 仲裁命名。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=106, symbol="Sg", nameZh="𨭆", nameEn="Seaborgium",
       atomicMass="269", category="transition-metal", period=7, group=6, groupLabel="VIB",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d⁴ 7s²", oxidationStates="+6",
       chemicalProperties="理论上应与钨（同族）化学性质相似，是首批经过化学研究的超重元素之一。",
       history="1974 年苏联杜布纳和美国伯克利合成，以格伦·西博格（Glenn Seaborg，镎和后续超铀元素的共同发现者）命名——首个以在世科学家命名的元素。",
       applications="基础核物理研究。",
       funFact="格伦·西博格是历史上唯一一位以在世状态看到以自己命名的元素被正式确认的科学家。西博格一生参与发现了 10 个超铀元素，是核化学史上贡献最大的科学家之一。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=107, symbol="Bh", nameZh="𨨏", nameEn="Bohrium",
       atomicMass="270", category="transition-metal", period=7, group=7, groupLabel="VIIB",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d⁵ 7s²", oxidationStates="+7",
       chemicalProperties="理论上应与铼（同族）化学性质相似。",
       history="1981 年德国 GSI 合成，以尼尔斯·玻尔（Niels Bohr，量子力学奠基人）命名。",
       applications="基础核物理研究。",
       funFact="玻尔于 1913 年提出氢原子的玻尔模型，用量子化轨道解释了氢的发射光谱，是量子力学发展的关键一步。以他命名的元素位于第七周期，象征着从经典到量子物理的跨越。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=108, symbol="Hs", nameZh="𨭆", nameEn="Hassium",
       atomicMass="277", category="transition-metal", period=7, group=8, groupLabel="VIII族",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d⁶ 7s²", oxidationStates="+8",
       chemicalProperties="理论上应与锇（同族）相似，OsO₄ 类比物 HsO₄ 已被实验证实，显示超重元素仍遵循周期律。",
       history="1984 年德国黑森州 GSI 合成，以黑森（Hessen）的拉丁语名 Hassia 命名。",
       applications="基础核物理研究。",
       funFact="科学家已成功合成并研究了 HsO₄ 分子，证明 108 号元素确实与同族的锇（76）性质相似——这是相对论量子化学预测和实验的重要验证，说明即使超重元素也服从周期律。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=109, symbol="Mt", nameZh="鿏", nameEn="Meitnerium",
       atomicMass="278", category="transition-metal", period=7, group=9, groupLabel="VIII族",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d⁷ 7s²", oxidationStates="+6",
       chemicalProperties="理论上应与铱（同族）化学性质相似，但尚无实验验证。",
       history="1982 年德国 GSI 合成，以莉泽·迈特纳（Lise Meitner，核裂变的理论阐释者）命名。",
       applications="基础核物理研究。",
       funFact="莉泽·迈特纳是核裂变的重要发现者之一，却因性别歧视未能与哈恩共同获得 1944 年诺贝尔奖，被诺贝尔委员会忽视。109 号元素以她命名，是科学史上迟来的认可。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=110, symbol="Ds", nameZh="鐽", nameEn="Darmstadtium",
       atomicMass="281", category="transition-metal", period=7, group=10, groupLabel="VIII族",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d⁸ 7s²", oxidationStates="+6",
       chemicalProperties="理论上应与铂（同族）化学性质相似，无实验验证。",
       history="1994 年德国达姆施塔特 GSI 合成，以发现地达姆施塔特（Darmstadt）命名。",
       applications="基础核物理研究。",
       funFact="GSI（亥姆霍兹重离子研究中心）位于德国达姆施塔特，是超重元素研究的重要基地，先后发现了从 107 到 112 号共 6 个元素，以一地之名命名其中一个，可谓实至名归。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=111, symbol="Rg", nameZh="錀", nameEn="Roentgenium",
       atomicMass="282", category="transition-metal", period=7, group=11, groupLabel="IB",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s¹", oxidationStates="+3",
       chemicalProperties="理论上应与金（同族）化学性质相似，相对论效应预测其化学性质可能更接近铊。",
       history="1994 年德国 GSI 合成，以威廉·伦琴（Wilhelm Röntgen，X 射线发现者）命名。",
       applications="基础核物理研究。",
       funFact="伦琴于 1895 年发现 X 射线，并因此获得第一届诺贝尔物理学奖（1901 年）。伦琴拒绝为 X 射线申请专利，使其免费用于医学——以他名字命名的元素是对这种无私精神的永久纪念。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=112, symbol="Cn", nameZh="鎶", nameEn="Copernicium",
       atomicMass="285", category="transition-metal", period=7, group=12, groupLabel="IIB",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s²", oxidationStates="+2",
       chemicalProperties="理论上应与汞（同族）相似，但相对论效应极强，预测其 7s 轨道大幅收缩，常温下可能为气态。",
       history="1996 年德国 GSI 合成，2010 年 IUPAC 正式命名，以尼古拉·哥白尼（Copernicus）命名。",
       applications="基础核物理研究。",
       funFact="鎶可能是元素周期表中第一个在室温下呈气态的金属——相对论量子力学计算显示，112 号元素因相对论效应使 7s 轨道强烈收缩，原子间结合力极弱，沸点可能低于室温，是真正的相对论元素。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  # ── Period 7 p-block: 113-118 ──────────────────────────────
  dict(atomicNumber=113, symbol="Nh", nameZh="鉨", nameEn="Nihonium",
       atomicMass="286", category="post-transition-metal", period=7, group=13, groupLabel="IIIA",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹", oxidationStates="+1, +3",
       chemicalProperties="理论上应与铊（同族）相似，是亚洲国家（日本）首次发现并命名的元素。",
       history="2004 年日本理化学研究所（RIKEN）合成，2016 年 IUPAC 正式命名，以日本（Nihon，日本语日本）命名。",
       applications="基础核物理研究。",
       funFact="113 号元素是亚洲国家首次独立发现并获得命名权的元素，日本 RIKEN 团队历经 9 年（2004-2012），用钙-48 轰击铋靶，总共合成了 3 个鉨原子，才获得 IUPAC 认可。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=114, symbol="Fl", nameZh="鈇", nameEn="Flerovium",
       atomicMass="289", category="post-transition-metal", period=7, group=14, groupLabel="IVA",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²", oxidationStates="+2",
       chemicalProperties="位于铅的正下方，但相对论效应预测其化学性质与铅差异显著，可能表现出类似惰性气体的化学不活泼性。",
       history="1998-1999 年俄美联合团队在杜布纳合成，2012 年 IUPAC 命名，以弗乔罗夫核反应实验室（Flerov Laboratory）命名。",
       applications="基础核物理研究。",
       funFact="114 号元素附近（Z≈114，N≈184）被理论预测为超重元素的稳定岛核心——受壳层效应保护，该区域的核素半衰期可能比相邻超重核长得多，实验探索正在进行中。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=115, symbol="Mc", nameZh="镆", nameEn="Moscovium",
       atomicMass="290", category="post-transition-metal", period=7, group=15, groupLabel="VA",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³", oxidationStates="+1, +3",
       chemicalProperties="理论上应与铋（同族）相似，无实验验证。",
       history="2003 年俄美联合团队在杜布纳合成，2016 年 IUPAC 以莫斯科（Moscow）命名。",
       applications="基础核物理研究。",
       funFact="镆是通过用 ²⁴⁸Cm 靶被 ⁴⁸Ca 离子轰击合成的——这种钙-48 同位素天然丰度仅 0.187%，极为稀少，需要专门浓缩，是合成超重元素的常用轰击弹头。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=116, symbol="Lv", nameZh="鉝", nameEn="Livermorium",
       atomicMass="293", category="post-transition-metal", period=7, group=16, groupLabel="VIA",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴", oxidationStates="+2",
       chemicalProperties="理论上应与钋（同族）相似，但相对论效应可能使其化学行为偏离预期。",
       history="2000 年俄美联合团队合成，2012 年 IUPAC 以美国利弗莫尔国家实验室（Lawrence Livermore National Laboratory）命名。",
       applications="基础核物理研究。",
       funFact="美国劳伦斯利弗莫尔国家实验室与俄罗斯联合原子核研究所（JINR）长期合作，共同合成了多个超重元素。这种冷战对手之间的科学合作，是人类共同探索物质边界的典范。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=117, symbol="Ts", nameZh="鿬", nameEn="Tennessine",
       atomicMass="294", category="halogen", period=7, group=17, groupLabel="VIIA",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵", oxidationStates="-1, +1",
       chemicalProperties="位于卤素族最底部，相对论效应预测其化学性质与传统卤素差异较大，可能表现出类金属特征。",
       history="2010 年俄美联合团队合成，2016 年 IUPAC 以田纳西州（Tennessee）命名，因该州有橡树岭国家实验室和范德比尔特大学参与研究。",
       applications="基础核物理研究。",
       funFact="鿬是迄今合成的第二重元素（仅次于奥加涅相），也是卤素族中最重的成员。合成鿬需要在橡树岭国家实验室特别制备的锫-249 靶，这一准备过程本身就耗费了多年时间和数百万美元。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),

  dict(atomicNumber=118, symbol="Og", nameZh="鿫", nameEn="Oganesson",
       atomicMass="294", category="noble-gas", period=7, group=18, groupLabel="0族",
       stateAtRoomTemp="未知（人工合成，半衰期极短）", density="—",
       meltingPoint=0, boilingPoint=0, electronegativity=None,
       electronConfiguration="[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶", oxidationStates="0",
       chemicalProperties="鿫位于稀有气体族最底部，但理论计算表明由于极强的相对论效应，其 7p 轨道扩展，电子结合能降低，可能实际上具有一定化学反应性，与传统稀有气体截然不同。",
       history="2002 年俄美联合团队在杜布纳合成，2016 年 IUPAC 以尤里·奥加涅相（Yuri Oganessian，超重元素研究先驱）命名——第二个以在世科学家命名的元素。",
       applications="基础核物理研究。",
       funFact="鿫是目前元素周期表中原子序数最大的元素，标志着第七周期的完成。理论预测鿫在常温下可能是固态（相对论效应使其沸点远高于氙），这将彻底颠覆稀有气体在常温下均为气态的认知。",
       educationalLinks=["[拓展] 人工合成元素、元素周期表的完善历史"]),
]

def element_to_ts(el):
    lines = ['  {']
    for k, v in el.items():
        if isinstance(v, list):
            if len(v) == 0:
                lines.append(f'    {k}: [],')
            else:
                lines.append(f'    {k}: [')
                for item in v:
                    lines.append(f'      {ts_str(item)},')
                lines.append('    ],')
        else:
            lines.append(f'    {k}: {ts_str(v)},')
    lines.append('  }')
    return '\n'.join(lines)

new_ts = ',\n\n'.join(element_to_ts(el) for el in elements)

# Remove trailing ]; and insert new elements
stripped = content.rstrip()
assert stripped.endswith('];'), f"Unexpected ending: {stripped[-20:]!r}"
body = stripped[:-2].rstrip()

new_content = body + ',\n\n' + new_ts + ',\n\n];\n'

with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
    f.write(new_content)

print(f'Done. Added {len(elements)} elements (Z=51-118).')
